### PR TITLE
Starting project conways with starter code from animation.

### PR DESCRIPTION
**Pull request by AWalnut1**
didnt actually do anything lol
also my old codespace is gone for some reason so i made a new one

### CODE REVIEW

**Comment by AWalnut1** [comment]
i have no idea what imm even doing on geting this grid to work, let alone cells

**Review by gigamonkey — CHANGES_REQUESTED** [review]
Let's talk in class about how you can tackle this.

**Comment by AWalnut1** [comment]
i can tell im oh so very close to getting this but the pieces jut aren't falling into place, luckily my home has internet again so i will be able to work on this at home.

**Comment by AWalnut1** [comment]
well i got the drawCell working. i swear im going to refactor it later

**Review by gigamonkey — APPROVED** [review]
Since you're working on Monty Hall now, maybe let's just leave this one until after Spring Break. We'll probably do one more project this year so maybe you can pick this up then and I can give you a bit more direction to get you going.

**Pull request merged**
